### ISSUE TITLE
What about PUT?

### ISSUE THREAD

**Issue by Hunter21007** [lvermeulen/Flurl.Http.Xml#10]
Hello, 

I have a question regarding put request. i can not find a method for it.
Do i miss something?

Thanks in advance

**Comment by lvermeulen** [comment]
No, you didn't miss anything. I have added Send & Put support in [v1.4.1](https://www.nuget.org/packages/Flurl.Http.Xml/1.4.1)

**Comment by Hunter21007** [comment]
Cool thanks!

Luk Vermeulen <notifications@github.com> schrieb am Fr., 16. Juni 2017,
17:58:
