### ISSUE TITLE
What am I missing in FLURL?

### ISSUE THREAD

**Issue by RyanSwan0** [lvermeulen/Flurl.Http.Xml#11]
This works:
//This text box is eating the XML tags for some reason.
string xml = "<grandparent><parent><child>123</child></parent></grandparent>";
string up = "user" + ":" + "pass";

var client = new HttpClient();
var byteArray = Encoding.ASCII.GetBytes(up); client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

var content = new StringContent(xml, Encoding.UTF8, "application/xml"); 
var response = client.PutAsync("https://url.org:8443/id/4", content).Result;

I get a 400 using this in flurl xml:

String ss = " https://url.org:8443/id/4"
//This text box is eating the XML tags for some reason.
string xml = "<grandparent><parent><child>123</child></parent></grandparent>";

await ss.WithBasicAuth("user", "pass").PutXmlAsync(xml);

What am I missing?

**Comment by lvermeulen** [comment]
I did a quick test:
```
    FlurlHttp.Configure(c => c.HttpClientFactory = new EchoHttpClientFactory());

    var result = await "http://some.url"
        .WithBasicAuth("user", "pass")
        .PutXmlAsync("123")
        .ReceiveXDocument();
```
Result is:
```
    <?xml version="1.0" encoding="utf-8"?>
    <string>123</string>
```
Not sure what's going on with the URL you're PUTting to.
