### ISSUE TITLE
Now broken since Flurl 2.0

### ISSUE THREAD

**Issue by steeleprice** [lvermeulen/Flurl.Http.Xml#12]
Need to update to support Flurl 2.0+ and the breaking changes.

**Comment by gitfool** [comment]
👍

**Comment by tmenier** [comment]
Great to see this is in the works. I'll tweet it out when it's up on NuGet. I do have some suggestions to get the code a little more in line with 2.0 though, I'll leave them as comments in the related [commit](https://github.com/lvermeulen/Flurl.Http.Xml/commit/0f95c92bc0b20b1d5bf49d51f16c9e1a229f547e).

**Comment by lvermeulen** [comment]
Much thanks, Todd! Your comments are the greatest.

**Comment by tmenier** [comment]
Glad to help!

**Comment by gitfool** [comment]
@lvermeulen I see 1.5.0 in [releases](https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/1.5.0) but not yet in [nuget.org](https://www.nuget.org/packages/Flurl.Http.Xml/)...

**Comment by ghost** [comment]
Any idea of when we might get a release of 1.5? Superstoked to test it out! 💃

**Comment by sandorfr** [comment]
Would be nice to have it on nuget :)

**Comment by lvermeulen** [comment]
Ugh. Release [1.5.0](https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/1.5.0) is on NuGet!
