### ISSUE TITLE
Is there a way to send an XML string instead of a model?

### ISSUE THREAD

**Issue by stecydube** [lvermeulen/Flurl.Http.Xml#13]
Essentially, I'm trying to convert this:

                var req = (HttpWebRequest)WebRequest.Create("http://blablabla.com");

                req.Credentials = CredentialCache.DefaultNetworkCredentials;
                req.Method = "POST";
                req.ContentType = "application/xml";

                UTF8Encoding utf8Enc = new UTF8Encoding();
                byte[] postBytes = utf8Enc.GetBytes(msg);

                req.ContentLength = postBytes.Length;

                using (Stream postStream = req.GetRequestStream())
                    postStream.Write(postBytes, 0, postBytes.Length);

                var resp = (HttpWebResponse)req.GetResponse();

**Comment by lvermeulen** [comment]
Well, you could simply call:

            var result = await "http://blablabla.com"
                .PostXmlAsync(msg)
                .ReceiveXmlResponseMessage();

And it's going to take care of UTF8 for you. I don't see what an XML string is, though. I mean, it's a model. :-)
