### ISSUE TITLE
>net core 2.1 & flurl 2.4

### ISSUE THREAD

**Issue by newportg** [lvermeulen/Flurl.Http.Xml#14]
Hi,

Can you rebuild your library with the current release of .net core and flurl, as I'm seeing multiple errors when I try to Get xml data.
Thanks

**Comment by lvermeulen** [comment]
I will update Flurl.Http to the latest version. Why would you want me to upgrade the .NET Core version, though?

**Comment by lvermeulen** [comment]
https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/1.6.0
