### ISSUE TITLE
HTTP Headers: Accept != Content-Type

### ISSUE THREAD

**Issue by vnikolov88** [lvermeulen/Flurl.Http.Xml#15]
When the Accept header is not the same as the Content-Type header, we get a crash in GetMediaType -> FlurlRequestExtensions.cs

`var content = new CapturedXmlContent(request.Settings.XmlSerializer().Serialize(data), request.GetMediaType());`

The problem is when you are creating the request the Mime Type of the content is taken from the Accept header definition not from Content-Type

`  var acceptHeaders = request.Headers
                .Where(x => x.Key == "Accept")
                .ToList();`

On top of this if you have any defined Accept header that is not for XML you are going to crash in 
`return mediaTypes.First(x => x.IndexOf("xml", StringComparison.OrdinalIgnoreCase) >= 0)
                ?? mediaTypes.First();`

This needs to be changed to 
`return mediaTypes.FirstOrDefault(x => x.IndexOf("xml", StringComparison.OrdinalIgnoreCase) >= 0)
                ?? mediaTypes.First();`

**Comment by lvermeulen** [comment]
I'm on it.

**Comment by lvermeulen** [comment]
I replaced .First() with .FirstOrDefault(), but I disagree with
> When the Accept header is not the same as the Content-Type header

Content-Type is a header on Content. Accept is a header on the request, and is the only header we should be looking at.

**Comment by vnikolov88** [comment]
in you implementation it is impossible to send xml and use ReceiveJson
after that to get the response as json

**Comment by lvermeulen** [comment]
Correct and I fixed that, would you mind having a look?

**Comment by lvermeulen** [comment]
Released in release [1.6.1](https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/1.6.1)
