### ISSUE TITLE
xml extensions for IFlurlResponse

### ISSUE THREAD

**Issue by tranb3r** [lvermeulen/Flurl.Http.Xml#17]
Hi,
I see that a PR with xml extensions for `IFlurlResponse` (new type introduced in Flurl 3.0.0-pre) was merged into the dev branch a few months ago.
Is there a plan to release a nuget package soon ?
Thanks

**Comment by lvermeulen** [comment]
Hi @tranb3r , no not really. Would you like a prerelease package?

**Comment by tranb3r** [comment]
Yes, I'd like to use Flurl 3.0.0-pre, and for that I need a pre-release package of Flurl.Http.Xml (with extensions for IFlurlResponse).

**Comment by lvermeulen** [comment]
I published a prerelease. :-)
