### ISSUE TITLE
Flurl 3.0.0 is out

### ISSUE THREAD

**Issue by tranb3r** [lvermeulen/Flurl.Http.Xml#18]
Hi Luk,

Flurl and Flurl.Http 3.0.0 have just been released.
Could you please publish a 2.0.0 of Flurl.Http.Xml ?

Thank you !
tranb3r

**Comment by lvermeulen** [comment]
Here you go: [2.0.0](https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/2.0.0) :-)
