### ISSUE TITLE
NET Core support

### ISSUE THREAD

**Issue by kroniak** [lvermeulen/Flurl.Http.Xml#2]
Please add NET Core (NET Standard 1.4 - 1.6) support to the package.

Flurl.Http 1.0.0 with net core 1.0.0 will be avaliable soon.

**Comment by lvermeulen** [comment]
I'll give it a go, not sure how far I will get with serialization though.

[Issue](https://github.com/lvermeulen/Flurl.Http.Xml/issues/3) created.

**Comment by lvermeulen** [comment]
@kroniak Where do I get the -Pre packages? Do you have an appveyor artifacts link I can use?

**Comment by kroniak** [comment]
@lvermeulen 

``` xml
<add key="flurl feed" value="https://www.myget.org/F/flurl/api/v3/index.json" /> 
```

It is myget feed. Soon this package will be avaliable at nuget.org feed.

https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-36/artifacts

**Comment by kroniak** [comment]
@lvermeulen If you want I can see and will do a PR.

**Comment by lvermeulen** [comment]
@kroniak Thanks for the links. I updated as far as I could; seems like beta7 doesn't support netstandard1.6 and netcoreapp1.0 yet, is that correct?

**Comment by kroniak** [comment]
@lvermeulen no, beta7 supports both.

**Comment by lvermeulen** [comment]
@kroniak Got it, thx.

**Comment by kroniak** [comment]
@lvermeulen packages on myget feed is obsolete, use nuget feed.
