### ISSUE TITLE
Support .NET Core RTM

### ISSUE THREAD

**Issue by lvermeulen** [lvermeulen/Flurl.Http.Xml#3]
Branch [feature/vnext](https://github.com/lvermeulen/Flurl.Http.Xml/tree/feature/vnext)
- [x] Flurl.Http.Xml
- [x] Flurl.Http.Xml.Tests
- [x] Build package
- [x] Update appveyor.yml
- [x] Use Flurl.Http 1.0.0
- [x] Merge to master

**Comment by lvermeulen** [comment]
@kroniak Awesome, thanks!!

**Comment by kroniak** [comment]
@lvermeulen please make a pr to master, need to check build on appveyor. PR can be merged to master after all points will done.

**Comment by lvermeulen** [comment]
@kroniak Pull request created

[Merge feature/vnext to master](https://github.com/lvermeulen/Flurl.Http.Xml/pull/5)

**Comment by lvermeulen** [comment]
Available as [Flurl.Http.Xml.1.3.0-alpha](https://www.nuget.org/packages/Flurl.Http.Xml/1.3.0-alpha)

**Comment by kroniak** [comment]
@lvermeulen I have update the Flurl.Http dependence.
Need to set a right version of NETSTD and release a new tag.

**Comment by lvermeulen** [comment]
Available as 1.3.0
