### ISSUE TITLE
text/xml Content Type

### ISSUE THREAD

**Issue by mattkoch614** [lvermeulen/Flurl.Http.Xml#9]
Is there a way to specify a Content-Type of `text/xml` when using this extension library? Out of the box it looks like all requests are tagged with an `application/xml` Content-Type.

**Comment by lvermeulen** [comment]
Do you mean when sending XML? If you can give some examples of what you are trying to achieve I will have a look.

**Comment by mattkoch614** [comment]
Yes, it has to do with sending. I'll get an example together ASAP and post it here.

**Comment by lvermeulen** [comment]
Release [1.4.0](https://github.com/lvermeulen/Flurl.Http.Xml/releases/tag/1.4.0) adds basic conneg.
